port: 8080
job_queue:
  capacity: 100
worker_pool:
  concurrency:
  backlog:
scheduler:
  repository_polling_interval: 60
consumer:
  job_queue_polling_interval: 5
repository:
  option: memory
  mysql:
    connection_max_lifetime:
    max_idle_connections:
    max_open_connections:
timeout_unit: second
logging_format: text