server:
  protocol: grpc
  http:
    port: 8080
  grpc:
    port: 50051
job_queue:
  option: rabbitmq
  memory_job_queue:
    capacity: 100
  rabbitmq:
    queue_params:
      name: job
      durable: false
      deleted_when_unused: false
      exclusive: false
      no_wait: false
    consume_params:
      name: rabbitmq-consumer
      auto_ack: true
      exclusive: false
      no_local: false
      no_wait: false
    publish_params:
      exchange: 
      routing_key: job
      mandatory: false
      immediate: false
worker_pool:
  concurrency:
  backlog:
scheduler:
  repository_polling_interval: 60
consumer:
  job_queue_polling_interval: 5
repository:
  option: mysql
  mysql:
    connection_max_lifetime:
    max_idle_connections:
    max_open_connections:
timeout_unit: second
logging_format: text