version: "3.8"

services:
  valet:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      - "/bin/sh"
      - "-c"
      - "go mod download && make build && /valet/valetd"
    environment:
      - MYSQL_DSN=root:password@tcp(mysql:3306)/valetdb?parseTime=true
      - RABBITMQ_URI=amqp://quest:password@rabbitmq:5672/
      - REDIS_URL=redis://redis
    depends_on:
      - mysql
      - rabbitmq
      - redis
    volumes:
      - ./:/valet
    ports:
      # HTTP port
      - 8080:8080
      # gRPC port
      - 50051:50051
  
  mysql:
    image: mysql:8
    command: mysqld --authentication-policy=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=valetdb
      - MYSQL_ROOT_USER=root  
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql/
  
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    environment:
       - RABBITMQ_DEFAULT_USER=quest
       - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:3.2-alpine
    command:
      - redis-server
      - --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
  mysql-data:
  rabbitmq-data:
  rabbitmq-log:
  redis-data: