version: "3.8"

services:
  valet:
    container_name: valet
    image: ${VALET_IMAGE_URL:-registry.valet.com/valet:latest}
    secrets:
      - source: mysql-dsn
        target: mysql_dsn
    working_dir: /valet
    command: /valet/valetd
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/api/status/
      interval: 30s
      timeout: 25s
      retries: 3

secrets:
  mysql-dsn:
    external:
      name: valet-mysql-dsn