version: "3.8"

services:
  valet:
    container_name: valet
    image: ${VALET_IMAGE_URL:-registry.valet.com/valet:latest}
    secrets:
      - source: mysql-dsn
        target: mysql_dsn
      - source: rabbitmq-uri
        target: rabbitmq_uri
      - source: redis-url
        target: redis_url
      - source: postgres-url
        target: postgres_url
    working_dir: /valet
    command: /valet/valetd
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/api/status/
      interval: 30s
      timeout: 25s
      retries: 3

secrets:
  mysql-dsn:
    external:
      name: valet-mysql-dsn
  rabbitmq-uri:
    external:
      name: valet-rabbitmq-uri
  redis-url:
    external:
      name: valet-redis-url
  postgres-url:
    external:
      name: valet-postgres-url