version: "3.8"

services:
  valet:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: build
    command:
      - "/bin/sh"
      - "-c"
      - "go mod download && make build && /valet/valetd"
    environment:
      - MYSQL_DSN=root:password@tcp(mysql:3306)/valetdb?parseTime=true&sql_mode=NO_ZERO_DATE
    volumes:
      - ./:/valet
    ports:
      - ${PORT:-8080}:8080
  
  mysql:
    image: mysql:8-oracle
    environment:
      - MYSQL_DATABASE=valetdb
      - MYSQL_ROOT_USER=root  
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql/

volumes:
  mysql-data: