basePath: /api
consumes:
- application/json
definitions:
  Duration:
    description: |-
      A Duration represents the elapsed time between two instants
      as an int64 nanosecond count. The representation limits the
      largest representable duration to approximately 290 years.
    format: int64
    type: integer
    x-go-package: time
  Job:
    properties:
      completed_at:
        description: CompletedAt is the UTC timestamp of the moment the job finished.
        format: date-time
        type: string
        x-go-name: CompletedAt
      created_at:
        description: CreatedAt is the UTC timestamp of the job creation.
        format: date-time
        type: string
        x-go-name: CreatedAt
      description:
        description: Description gives some information about the job.
        type: string
        x-go-name: Description
      duration:
        $ref: '#/definitions/Duration'
      failure_reason:
        description: FailureReason holds the error message that led to the job failure,
          if any.
        type: string
        x-go-name: FailureReason
      id:
        description: ID is the auto-generated job identifier in UUID4 format.
        type: string
        x-go-name: ID
      name:
        description: Name is the name of the job.
        type: string
        x-go-name: Name
      next:
        $ref: '#/definitions/Job'
      next_job_id:
        description: NextJobID is the ID of the job that should run next in the pipeline,
          if any.
        type: string
        x-go-name: NextJobID
      pipeline_id:
        description: |-
          PipelineID is the auto-generated pipeline identifier in UUID4 format.
          It will be empty if the job does not belong to a pipeline.
        type: string
        x-go-name: PipelineID
      run_at:
        description: RunAt is the UTC timestamp indicating the time for the job to
          run.
        format: date-time
        type: string
        x-go-name: RunAt
      scheduled_at:
        description: ScheduledAt is the UTC timestamp indicating the time that the
          job got scheduled.
        format: date-time
        type: string
        x-go-name: ScheduledAt
      started_at:
        description: StartedAt is the UTC timestamp of the moment the job started.
        format: date-time
        type: string
        x-go-name: StartedAt
      status:
        $ref: '#/definitions/JobStatus'
      task_name:
        description: TaskName is the name of the task to be executed.
        type: string
        x-go-name: TaskName
      task_params:
        additionalProperties:
          type: object
        description: TaskParams are the required parameters for the task assigned
          to the specific job.
        type: object
        x-go-name: TaskParams
      timeout:
        description: Timeout is the time in seconds after which the job task will
          be interrupted.
        format: int64
        type: integer
        x-go-name: Timeout
      use_previous_results:
        description: |-
          UsePreviousResults indicates where the job should use the
          results of the previous job in the pipeline or not.
        type: boolean
        x-go-name: UsePreviousResults
    title: Job represents an async task.
    type: object
    x-go-package: github.com/svaloumas/valet/internal/core/domain
  JobResult:
    properties:
      error:
        type: string
        x-go-name: Error
      job_id:
        type: string
        x-go-name: JobID
      metadata:
        type: object
        x-go-name: Metadata
    title: JobResult contains the result of a job.
    type: object
    x-go-package: github.com/svaloumas/valet/internal/core/domain
  JobStatus:
    format: int64
    title: JobStatus holds a value for job status ranging from 1 to 5.
    type: integer
    x-go-package: github.com/svaloumas/valet/internal/core/domain
  Pipeline:
    properties:
      completed_at:
        description: CompletedAt is the UTC timestamp of the moment the pipeline finished.
        format: date-time
        type: string
        x-go-name: CompletedAt
      created_at:
        description: CreatedAt is the UTC timestamp of the pipeline creation.
        format: date-time
        type: string
        x-go-name: CreatedAt
      description:
        description: Description gives some information about the pipeline.
        type: string
        x-go-name: Description
      duration:
        $ref: '#/definitions/Duration'
      id:
        description: ID is the auto-generated pipeline identifier in UUID4 format.
        type: string
        x-go-name: ID
      jobs:
        description: Jobs represents the jobs included to this pipeline.
        items:
          $ref: '#/definitions/Job'
        type: array
        x-go-name: Jobs
      name:
        description: Name is the name of the pipeline.
        type: string
        x-go-name: Name
      run_at:
        description: |-
          RunAt is the UTC timestamp indicating the time for the pipeline to run.
          This property will be propagated to the first job of the pipeline.
        format: date-time
        type: string
        x-go-name: RunAt
      started_at:
        description: StartedAt is the UTC timestamp of the moment the pipeline started.
        format: date-time
        type: string
        x-go-name: StartedAt
      status:
        $ref: '#/definitions/JobStatus'
    title: Pipeline represents a sequence of async tasks.
    type: object
    x-go-package: github.com/svaloumas/valet/internal/core/domain
  RequestBodyDTO:
    properties:
      description:
        type: string
        x-go-name: Description
      jobs:
        items:
          $ref: '#/definitions/RequestBodyDTO'
        type: array
        x-go-name: Jobs
      name:
        type: string
        x-go-name: Name
      run_at:
        type: string
        x-go-name: RunAt
    title: RequestBodyDTO is the data transfer object used for a job creation or update.
    type: object
    x-go-package: github.com/svaloumas/valet/internal/handler/pipelinehdl
  errResponse:
    properties:
      code:
        format: int64
        type: integer
        x-go-name: Code
      error:
        type: boolean
        x-go-name: Error
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/svaloumas/valet/doc/swagger
host: localhost:8080
info:
  description: Documentation of the valet API.
  title: valet
  version: 0.8.0
paths:
  /jobs:
    get:
      operationId: getJobs
      parameters:
      - description: The status of the jobs to be fetched..
        in: query
        name: status
        type: string
        x-go-name: Status
      responses:
        "200":
          $ref: '#/responses/getJobsResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns all jobs, optionally filters them by status.
      tags:
      - jobs
    post:
      operationId: createJobs
      parameters:
      - description: Name, description and metadata of the new job to be performed.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/RequestBodyDTO'
      responses:
        "202":
          $ref: '#/responses/postJobsResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Creates a new job.
      tags:
      - jobs
  /jobs/{id}:
    delete:
      operationId: deleteJob
      parameters:
      - description: The ID of the specified job.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "204":
          description: ""
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Deletes a specified job.
      tags:
      - jobs
    get:
      operationId: getJob
      parameters:
      - description: The ID of the specified job.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/getJobResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns a specified job.
      tags:
      - jobs
    patch:
      operationId: patchJob
      parameters:
      - description: The ID of the specified job.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "204":
          description: ""
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Updates a job's name or description.
      tags:
      - jobs
  /jobs/{id}/results:
    delete:
      operationId: deleteJobResults
      parameters:
      - description: The ID of the specified job.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "204":
          description: ""
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Deletes a job's results.
      tags:
      - jobs
    get:
      operationId: getJobResults
      parameters:
      - description: The ID of the specified job.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/getJobResultsResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns a specified job's results.
      tags:
      - jobs
  /pipelines:
    get:
      operationId: getPipelines
      parameters:
      - description: The status of the pipelines to be fetched..
        in: query
        name: status
        type: string
        x-go-name: Status
      responses:
        "200":
          $ref: '#/responses/getPipelinesResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns all pipelines, optionally filters them by status.
      tags:
      - pipelines
    post:
      operationId: createPipelines
      parameters:
      - description: Name, description and metadata of the new pipeline to be performed.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/RequestBodyDTO'
      responses:
        "202":
          $ref: '#/responses/postPipelinesResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Creates a new pipeline.
      tags:
      - pipelines
  /pipelines/{id}:
    delete:
      operationId: deletePipeline
      parameters:
      - description: The ID of the specified pipeline.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "204":
          description: ""
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Deletes a specified pipeline.
      tags:
      - pipelines
    get:
      operationId: getPipeline
      parameters:
      - description: The ID of the specified pipeline.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/getPipelineResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns a specified pipeline.
      tags:
      - pipelines
    patch:
      operationId: patchPipeline
      parameters:
      - description: The ID of the specified pipeline.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "204":
          description: ""
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Updates a pipeline's name or description.
      tags:
      - pipelines
  /pipelines/{id}/jobs:
    get:
      operationId: getPipelineJobs
      parameters:
      - description: The ID of the specified pipeline.
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/getPipelineJobsResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Returns the jobs of the specified pipeline.
      tags:
      - pipelines
produces:
- application/json
responses:
  errorResponse:
    description: The API error response body.
    schema:
      $ref: '#/definitions/errResponse'
  getJobResponse:
    description: The specified job's metadata.
    schema:
      $ref: '#/definitions/Job'
  getJobResultsResponse:
    description: Returns a specified job results.
    schema:
      $ref: '#/definitions/JobResult'
  getJobsResponse:
    description: The jobs metadata.
    schema:
      properties:
        jobs:
          items:
            $ref: '#/definitions/Job'
          type: array
          x-go-name: Jobs
      type: object
  getPipelineJobsResponse:
    description: The pipeline jobs metadata.
    schema:
      properties:
        jobs:
          items:
            $ref: '#/definitions/Job'
          type: array
          x-go-name: Jobs
      type: object
  getPipelineResponse:
    description: The specified pipeline's metadata.
    schema:
      $ref: '#/definitions/Pipeline'
  getPipelinesResponse:
    description: The pipelines metadata.
    schema:
      properties:
        pipelines:
          items:
            $ref: '#/definitions/Pipeline'
          type: array
          x-go-name: Pipelines
      type: object
  postJobsResponse:
    description: Returns the newly created job metadata.
    schema:
      $ref: '#/definitions/Job'
  postPipelinesResponse:
    description: Returns the newly created pipeline metadata.
    schema:
      $ref: '#/definitions/Pipeline'
schemes:
- http
swagger: "2.0"
