name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Build and spawn the containers
      run: docker-compose up -d mysql postgres rabbitmq redis
    - name: Test
      run: make test

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Build and spawn the containers
      run: docker-compose up -d mysql postgres rabbitmq redis

    - name: Coverage report
      run: make report
    - name: verify coverage.out
      run: cat coverage.out

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        flags: unittests
        name: codecov-coverage
        fail_ci_if_error: true
        verbose: true